/* the application simulates the solar system using svg and realistic physics */
var svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
svg.setAttribute('width', '100%');
svg.setAttribute('height', '100%');
svg.setAttribute('viewBox', '0 0 100 100');
document.body.appendChild(svg);
var sun = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
sun.setAttribute('cx', '50');
sun.setAttribute('cy', '50');
sun.setAttribute('r', '40');
sun.setAttribute('fill', 'yellow');
svg.appendChild(sun);
var earth = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
earth.setAttribute('cx', '50');
earth.setAttribute('cy', '50');
earth.setAttribute('r', '10');
earth.setAttribute('fill', 'blue');
svg.appendChild(earth);
var moon = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
moon.setAttribute('cx', '50');
moon.setAttribute('cy', '50');
moon.setAttribute('r', '5');
moon.setAttribute('fill', 'white');
svg.appendChild(moon);
var earthOrbit = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
earthOrbit.setAttribute('cx', '50');
earthOrbit.setAttribute('cy', '50');
earthOrbit.setAttribute('r', '30');
earthOrbit.setAttribute('fill', 'none');
earthOrbit.setAttribute('stroke', 'blue');
earthOrbit.setAttribute('stroke-width', '1');
svg.appendChild(earthOrbit);
var moonOrbit = document.createElementNS('http://www.w3.org/2000/svg', 'circle');
moonOrbit.setAttribute('cx', '50');
moonOrbit.setAttribute('cy', '50');
moonOrbit.setAttribute('r', '25');
moonOrbit.setAttribute('fill', 'none');
moonOrbit.setAttribute('stroke', 'white');
moonOrbit.setAttribute('stroke-width', '1');
svg.appendChild(moonOrbit);
var earthVelocity = 0.01;
var moonVelocity = 0.005;
var earthAngle = 0;
var moonAngle = 0;
var earthOrbitRadius = 30;
var moonOrbitRadius = 25;
var earthOrbitAngle = 0;
var moonOrbitAngle = 0;
var earthOrbitSpeed = 0.01;
var moonOrbitSpeed = 0.005;
function update() {
  earthAngle += earthVelocity;
  moonAngle += moonVelocity;
  earthOrbitAngle += earthOrbitSpeed;
  moonOrbitAngle += moonOrbitSpeed;
  earth.setAttribute('cx', (50 + earthOrbitRadius * Math.cos(earthOrbitAngle)));
  earth.setAttribute('cy', (50 + earthOrbitRadius * Math.sin(earthOrbitAngle)));
  moon.setAttribute('cx', (50 + moonOrbitRadius * Math.cos(moonOrbitAngle)));
  moon.setAttribute('cy', (50 + moonOrbitRadius * Math.sin(moonOrbitAngle)));
  earthOrbit.setAttribute('cx', (50 + earthOrbitRadius * Math.cos(earthOrbitAngle)));
  earthOrbit.setAttribute('cy', (50 + earthOrbitRadius * Math.sin(earthOrbitAngle)));
  moonOrbit.setAttribute('cx', (50 + moonOrbitRadius * Math.cos(moonOrbitAngle)));
  moonOrbit.setAttribute('cy', (50 + moonOrbitRadius * Math.sin(moonOrbitAngle)));
  requestAnimationFrame(update);
}
update();
